# Generated by Django 3.0.3 on 2020-03-01 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('profissao', models.CharField(max_length=50, verbose_name='Profissão')),
            ],
        ),
        migrations.CreateModel(
            name='Dono',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cpf', models.IntegerField(primary_key=True, serialize=False, verbose_name='CPF')),
                ('cargo', models.CharField(max_length=50, verbose_name='Cargo')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
            ],
        ),
    ]
